# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'mimemagic'

gem 'ffi-rzmq'
gem 'iruby'

gem 'pycall', ">= 1.3.0"
gem 'matplotlib'

gem 'charty', path: ".."

gem 'gruff'
gem 'rubyplot'

gem 'red-datasets'
gem 'red-datasets-daru'
gem 'numo-narray'
gem 'nmatrix'

gem 'rails'
gem 'sqlite3', '~> 1.3.6'
gem 'red-colors'
